### ISSUE TITLE
Failed to get CSS for route

### ISSUE THREAD

**Issue by estebansa19** [mudbugmedia/critical-path-css-rails#46]
Hi, I got the following error when I run `CriticalPathCss.generate_all` or `rake critical_path_css:generate`.

Error: Penthouse timed out after 60s. 
Failed to get CSS for route /
  with options={"url"=>"http://local.ayendarooms:3000/", "css"=>"/home/esteban/Desktop/ayenda/public/assets/distributions/application.css", "width"=>1300, "height"=>900, "timeout"=>60000, "forceInclude"=>[], "strict"=>false, "maxEmbeddedBase64Length"=>1000, "userAgent"=>"Penthouse Critical Path CSS Generator", "renderWaitTime"=>100, "blockJSRequests"=>true, "customPageHeaders"=>{"Accept-Encoding"=>"identity"}}

I checked and the file exists. Any help will be very useful, thanks

**Comment by ck2000** [comment]
Same here... any ideas?

**Comment by michael-misshore** [comment]
@estebansa19 and @ck2000 Can either of you `ping` or `telnet` that URL:Port from the same location/command prompt that you are running the rake command? The timeout error may be an indication that the URL is unreachable/not visible from the place you're running `rake critical_path_css:generate`.

**Comment by michael-misshore** [comment]
I'm going to close this issue for now, as I don't believe this is an issue with the gem itself. Feel free to re-open if more debugging turns up otherwise.

**Comment by ck2000** [comment]
I am still getting

> Error: ENOENT: no such file or directory, open '/assets/website/application-web-b58f65d3d5d4b92a81734388926148c43905e9f0abab43b8faa4fa214b73ec99.css'
Failed to get CSS for route /

Well, I can access localhost:3000 as usual via my browser. Ping localhost also succeeds. If I open the URL in the browser, the css file is loaded. The OSX Firewall is turned off. I don't know what to do...

**Comment by michael-misshore** [comment]
@ck2000 Looks like you're no longer getting the timeout error initially reported by the OP, which is good. Can you send me your config yaml, rails version, and version of this gem that you are using?

Your issue is now more related to #45. With the info you provide above, I should be able to determine if this is still an issue with the gem.

**Comment by ck2000** [comment]
Thank you for your quick response:
> ruby -v
> ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin17]

GEMFILE

> gem 'rails', '5.2.3'
> gem 'critical-path-css-rails', '~> 3.1.0'

gem -v critical-path-css-rails 

> 2.7.8

critical_path_css.yml
```
defaults: &defaults
  # If using the asset pipeline, provide the manifest name
  manifest_name: website/application-web
  # Else provide the relative path of your CSS file from the /public directory
  # css_path: /path/to/css/from/public/main.css
  # Or provide a separate path for each route
  # css_paths:
  #   - /path/to/css/from/public/main.css
  routes:
    - /

development:
  <<: *defaults
  base_url: http://localhost:3000
```
